apiVersion: v1
kind: Service
metadata:
  name: hms-patient-mgmt-svc
spec:
  selector:
    app: hms-patient-mgmt-pod
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-patient-mgmt-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-patient-mgmt-pod
  template:
    metadata:
      labels:
        app: hms-patient-mgmt-pod
    spec:
      serviceAccountName: hms-pods-sa
      containers:
      - name: hms-patient-mgmt-app
        image: somnathbm/hms-patient-mgmt-svc:v0.0.5
        ports:
        - name: web
          containerPort: 8080
        envFrom:
        - secretRef:
            name: hms-patient-mgmt-secret