apiVersion: v1
kind: Service
metadata:
  name: hms-patient-mgmt-svc
  labels:
    app: hms-patient-mgmt-svc
spec:
  selector:
    app: hms-patient-mgmt-pod
  ports:
  - name: app-port
    protocol: TCP
    port: 80
    targetPort: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-patient-mgmt-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-patient-mgmt-pod
  template:
    metadata:
      labels:
        app: hms-patient-mgmt-pod
    spec:
      serviceAccountName: hms-pods-sa
      containers:
      - name: hms-patient-mgmt-app
        image: somnathbm/hms-patient-mgmt-svc:v0.0.6
        livenessProbe:
          httpGet:
            path: /pm/healthy
            port: app
          initialDelaySeconds: 10
          periodSeconds: 20
        ports:
        - name: app
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        envFrom:
        - secretRef:
            name: hms-patient-mgmt-secret