apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-patient-mgmt-depl
spec:
  template:
    metadata:
      labels:
        app: hms-patient-mgmt-pod
    spec:
      containers:
      - name: hms-patient-mgmt-app
        envFrom:
        - secretRef:
          name: hms-patient-mgmt-secret-stage