apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: hms-patient-mgmt-pm
  namespace: hms-dev
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: hms-patient-mgmt-pod
  namespaceSelector:
    matchNames:
    - hms-dev
  podMetricsEndpoints:
  - port: http-web
    path: /metrics