apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hms-patient-mgmt-sm
  namespace: hms-dev
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: hms-patient-mgmt-svc
  namespaceSelector:
    matchNames:
    - hms-dev
  endpoints:
  - port: http-web
    path: /metrics