resources:
- ../base

nameSuffix: -prod
namespace: hms-prod

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hms-patient-mgmt-depl
    path: patch-secret-ref.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hms-patient-mgmt-depl
    path: patch-service-account.yaml
    